[build]
  command = "npm run build"
  publish = ".next"
  [build.environment]
    NODE_VERSION = "20"
    # These NEXT_PUBLIC_* keys are intentionally exposed to the client.
    # Omit them from Netlify secrets scanning to avoid false positives.
    SECRETS_SCAN_OMIT_KEYS = "NEXT_PUBLIC_SUPABASE_ANON_KEY,NEXT_PUBLIC_SUPABASE_URL"

[[plugins]]
  package = "@netlify/plugin-nextjs"

